name: bestco_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  go_router: ^10.0.0
  flutter_riverpod: ^2.3.6
  flex_color_scheme: ^7.3.1
  google_fonts: ^5.1.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^8.0.0
  loading_indicator: ^3.1.1
  form_field_validator: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  iconsax: ^0.0.8
  calendar_timeline: ^1.1.2
  shimmer: ^3.0.0
  flutter_survey: ^0.1.4
  progress_stepper: ^1.0.0
  table_calendar: ^3.0.9
  flutter_calendar_carousel: ^2.4.2
  flutter_svg: ^2.0.7
  synchronized: ^3.1.0
  jiffy: ^6.2.1
  uuid: ^3.0.7
  dio: ^5.3.2
  permission_handler: ^10.4.3
  file_picker: ^5.3.3
  http_parser: ^4.0.2
  url_launcher: ^6.1.12
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_messaging: ^14.6.7
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  firebase_crashlytics: ^3.3.5
  google_maps_flutter: ^2.4.0
  dropdown_search: ^5.0.6
  audio_waveforms: ^1.0.4
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  flutter_spinkit: ^5.1.0
#  image_picker_plus: ^0.5.9
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  photo_view: ^0.14.0
  syncfusion_flutter_pdfviewer: ^22.2.12
  syncfusion_flutter_datepicker: ^22.2.12
  restart_app: ^1.2.1
  flutter_phoenix: ^1.1.1
  flutter_local_notifications: ^15.1.1
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  chips_choice: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.1
  faker: ^2.1.0
  json_annotation: ^4.8.1
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  pub_semver: ^2.1.4
  custom_lint:
  riverpod_lint:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/demo/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/gif/
    - assets/svg/
    - assets/logo/
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: Localization
  main_locale: ar
  arb_dir: lib/locales/l10n
  output_dir: lib/locales/localization


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
#
#flutter_native_splash:
#  color: "#ffffff"
#  icon_background_color: "#111111"
#  image: assets/logo/logo_name.png