// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZClablQU1W9NGuR01KiNW38XYMU5MuV8',
    appId: '1:692009010479:web:e790b59b5ce9dd2a980dda',
    messagingSenderId: '692009010479',
    projectId: 'fire-watch-2024',
    authDomain: 'fire-watch-2024.firebaseapp.com',
    storageBucket: 'fire-watch-2024.appspot.com',
    measurementId: 'G-259V7R55RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDudToZ-iFSLq7oGYKYaveebJMdazmVMAU',
    appId: '1:692009010479:android:b8ed082dbb3f5b03980dda',
    messagingSenderId: '692009010479',
    projectId: 'fire-watch-2024',
    storageBucket: 'fire-watch-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-X1ZHWlMVwH8GRcXBYaZaDuBBghmDeE',
    appId: '1:692009010479:ios:b274cb50f4e7344d980dda',
    messagingSenderId: '692009010479',
    projectId: 'fire-watch-2024',
    storageBucket: 'fire-watch-2024.appspot.com',
    iosClientId: '692009010479-si918r0k7daq7h8nt7dr7qmp22f4lptn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt-X1ZHWlMVwH8GRcXBYaZaDuBBghmDeE',
    appId: '1:692009010479:ios:b274cb50f4e7344d980dda',
    messagingSenderId: '692009010479',
    projectId: 'fire-watch-2024',
    storageBucket: 'fire-watch-2024.appspot.com',
    iosClientId: '692009010479-si918r0k7daq7h8nt7dr7qmp22f4lptn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireMate',
  );
}
